name: Publish 'basic' theme

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'MadeByEmil/Pigmeat'
    - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          override: true
          components: rust-src
    - name: Build Dokkoo binary
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --all-features --target x86_64-unknown-linux-gnu
    - name: Prepare Dokkoo binary
      run: |
        strip -v --strip-all ./target/x86_64-unknown-linux-gnu/release/dokkoo
        chmod +x ./target/x86_64-unknown-linux-gnu/release/dokkoo
    - name: Install 'grass' for Sass rendering
      run: |
        cargo install grass
    - uses: actions/checkout@v2
      with:
        path: ./target/x86_64-unknown-linux-gnu/release/basic
    - name: Build 'basic' Mokk
      run: |
        cd ./target/x86_64-unknown-linux-gnu/release
        cp -avr ./basic/* ./
        rm -rf ./basic/
        rm -rf ./output
        ./dokkoo build .
        mkdir -p ./output/_css/
        grass ./sass/basic.scss > ./output/_css/basic.css
        cp -avf ./robots.txt ./output
    - name: Output current directory listing
      run: |
        cd ./target/x86_64-unknown-linux-gnu/release/output/
        ls
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./bin/Release/netcoreapp3.1/output/
        publish_branch: gh-pages  # deploying branch
        user_name: Dokkoo
        user_email: em@emsa.cf
        commit_message: "Building 'basic' Mokk"
